<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class AttractionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("attractions")->insert([
            //parque 1
            // --- SUAVES ---
            [
                "name" => "Vórtice Marino",
                "type" => "moderado",
                "description" => "Experimenta la atracción definitiva para parejas. Deslízate por giros cerrados y déjate llevar por un vórtice gigante que te hará sentir la verdadera fuerza del agua. Una combinación única de velocidad, embudos y mucha diversión.",
                "duration" => 3,
                "max_capacity" => 30,
                "min_height" => 0.00,
                "status" => "operational",
                "park_id" => 1,
                "image" => "atraccion1.png",
                "created_at" => "2026-03-20 10:00:00",
                "updated_at" => "2026-03-20 10:00:00",
            ],
            [
                "name" => "Carrera de Mantarrayas",
                "type" => "suave",
                "description" => "¡Siente el planeo del océano! En Carrera de Mantarrayas competirás cara a cara en un descenso vertiginoso. Emula el movimiento de estos gigantes del mar y llega primero a la meta en una explosión de agua y adrenalina.",
                "duration" => 10,
                "max_capacity" => 12,
                "min_height" => 0.90,
                "status" => "operational",
                "park_id" => 1,
                "image" => "image2.png",
                "created_at" => "2026-03-25 11:30:00",
                "updated_at" => "2026-03-25 11:30:00",
            ],
            [
                "name" => "Arrecife del Tiburón Cubeta",
                "type" => "suave",
                "description" => "Diversión al límite en nuestra gran estructura interactiva! Explora niveles llenos de toboganes y chorros. Pero cuidado... un tiburón hambriento vigila la cima. Cuando el gigantesco cubo se llena, prepárate para un chapuzón colosal e inolvidable.",
                "duration" => 5,
                "max_capacity" => 4,
                "min_height" => 0.80,
                "status" => "maintenance",
                "park_id" => 1,
                "image" => "image3.png",
                "created_at" => "2026-04-01 09:15:00",
                "updated_at" => "2026-04-01 09:15:00",
            ],
            [
                "name" => "Caída del Calamar Gigante",
                "type" => "intenso",
                "description" => "Siente la fuerza de los tentáculos en esta caída libre de colores. Deslízate a toda velocidad por túneles serpenteantes que desafían la gravedad. Ideal para los valientes que buscan la máxima emoción en Mundo Marino. ¿Te atreves a lanzarte al abismo?",
                "duration" => 5,
                "max_capacity" => 20,
                "min_height" => 1.10,
                "status" => "operational",
                "park_id" => 1,
                "image" => "image4.png",
                "created_at" => "2026-03-20 10:00:00",
                "updated_at" => "2026-03-20 10:00:00",
            ],
            [
                "name" => "La Cueva Abisal",
                "type" => "moderado",
                "description" => "Sumérgete en la oscuridad total de La Cueva Abisal. Deslízate por un tubo negro donde perderás la noción del tiempo y el espacio hasta que una explosión de luz y agua te devuelva a la superficie. ¿Te atreves con el misterio del fondo marino?",
                "duration" => 6,
                "max_capacity" => 8,
                "min_height" => 1.20,
                "status" => "operational",
                "park_id" => 1,
                "image"=>"image6.png",
                "created_at" => "2026-03-28 14:20:00",
                "updated_at" => "2026-03-28 14:20:00",
            ],
            [
                "name" => "Cataratas Misteriosas",
                "type" => "moderado",
                "description" => "Caída libre hacia una cueva.",
                "duration" => 4,
                "max_capacity" => 16,
                "min_height" => 1.15,
                "status" => "closed",
                "park_id" => 1,
                "image" => "https://lh3.googleusercontent.com/aida-public/AB6AXuCFsEt5IDp4eM3zxQA_qXlmCTKvlR_kWL1l9nQ2uAotEcuvEHEggiUvGBRn8Qwx3jKLnhW2Frj7gBCi8egjueurnHnF5NkqrZJVILn4VPbo2afG-zyvZIfgsBrnRoe-MkMQjdJc5TdAsseFh8rB6HqJRlcWdDoXQTC0wFvNMSPGk-PbMcW7orrjtyDQEJqvTiaUzLAAZMGQ-4ldr4OtJZ1o3DoKPpGWdAt5NNDOocklyDyvny298A7zwtA0g4mIhwnjsWyl__BA4arG",
                "created_at" => "2026-04-03 17:45:00",
                "updated_at" => "2026-04-03 17:45:00",
            ],
            [
                "name" => "El Remolino",
                "type" => "intenso",
                "description" => "Giros vertiginosos y caídas.",
                "duration" => 2,
                "max_capacity" => 24,
                "min_height" => 1.40,
                "status" => "operational",
                "park_id" => 1,
                "image" => "https://lh3.googleusercontent.com/aida-public/AB6AXuCFsEt5IDp4eM3zxQA_qXlmCTKvlR_kWL1l9nQ2uAotEcuvEHEggiUvGBRn8Qwx3jKLnhW2Frj7gBCi8egjueurnHnF5NkqrZJVILn4VPbo2afG-zyvZIfgsBrnRoe-MkMQjdJc5TdAsseFh8rB6HqJRlcWdDoXQTC0wFvNMSPGk-PbMcW7orrjtyDQEJqvTiaUzLAAZMGQ-4ldr4OtJZ1o3DoKPpGWdAt5NNDOocklyDyvny298A7zwtA0g4mIhwnjsWyl__BA4arG",
                "created_at" => "2026-03-20 10:00:00",
                "updated_at" => "2026-03-20 10:00:00",
            ],
            [
                "name" => "Tifón Infernal",
                "type" => "intenso",
                "description" => "Montaña rusa de alta velocidad.",
                "duration" => 2,
                "max_capacity" => 20,
                "min_height" => 1.50,
                "status" => "maintenance",
                "park_id" => 1,
                "image" => "https://lh3.googleusercontent.com/aida-public/AB6AXuCFsEt5IDp4eM3zxQA_qXlmCTKvlR_kWL1l9nQ2uAotEcuvEHEggiUvGBRn8Qwx3jKLnhW2Frj7gBCi8egjueurnHnF5NkqrZJVILn4VPbo2afG-zyvZIfgsBrnRoe-MkMQjdJc5TdAsseFh8rB6HqJRlcWdDoXQTC0wFvNMSPGk-PbMcW7orrjtyDQEJqvTiaUzLAAZMGQ-4ldr4OtJZ1o3DoKPpGWdAt5NNDOocklyDyvny298A7zwtA0g4mIhwnjsWyl__BA4arG",
                "created_at" => "2026-03-30 12:00:00",
                "updated_at" => "2026-03-30 12:00:00",
            ],
            [
                "name" => "Abismo del Kraken",
                "type" => "intenso",
                "description" => "La caída más alta del parque.",
                "duration" => 3,
                "max_capacity" => 12,
                "min_height" => 1.45,
                "status" => "operational",
                "park_id" => 1,
                "image" => "https://lh3.googleusercontent.com/aida-public/AB6AXuCFsEt5IDp4eM3zxQA_qXlmCTKvlR_kWL1l9nQ2uAotEcuvEHEggiUvGBRn8Qwx3jKLnhW2Frj7gBCi8egjueurnHnF5NkqrZJVILn4VPbo2afG-zyvZIfgsBrnRoe-MkMQjdJc5TdAsseFh8rB6HqJRlcWdDoXQTC0wFvNMSPGk-PbMcW7orrjtyDQEJqvTiaUzLAAZMGQ-4ldr4OtJZ1o3DoKPpGWdAt5NNDOocklyDyvny298A7zwtA0g4mIhwnjsWyl__BA4arG",
                "created_at" => "2026-04-05 16:30:00",
                "updated_at" => "2026-04-05 16:30:00",
            ],
            [
                "name" => "Gran Carrusel Real",
                "type" => "suave",
                "description" => "Versión de lujo del carrusel clásico.",
                "duration" => 3,
                "max_capacity" => 35,
                "min_height" => 0.00,
                "status" => "operational",
                "park_id" => 2,
                "image" => "https://lh3.googleusercontent.com/aida-public/AB6AXuCFsEt5IDp4eM3zxQA_qXlmCTKvlR_kWL1l9nQ2uAotEcuvEHEggiUvGBRn8Qwx3jKLnhW2Frj7gBCi8egjueurnHnF5NkqrZJVILn4VPbo2afG-zyvZIfgsBrnRoe-MkMQjdJc5TdAsseFh8rB6HqJRlcWdDoXQTC0wFvNMSPGk-PbMcW7orrjtyDQEJqvTiaUzLAAZMGQ-4ldr4OtJZ1o3DoKPpGWdAt5NNDOocklyDyvny298A7zwtA0g4mIhwnjsWyl__BA4arG",
                "created_at" => "2026-03-20 10:00:00",
                "updated_at" => "2026-03-20 10:00:00",
            ],
            [
                "name" => "Crucero del Canal",
                "type" => "suave",
                "description" => "Paseo panorámico por el segundo parque.",
                "duration" => 12,
                "max_capacity" => 15,
                "min_height" => 0.90,
                "status" => "operational",
                "park_id" => 2,
                "image" => "https://lh3.googleusercontent.com/aida-public/AB6AXuCFsEt5IDp4eM3zxQA_qXlmCTKvlR_kWL1l9nQ2uAotEcuvEHEggiUvGBRn8Qwx3jKLnhW2Frj7gBCi8egjueurnHnF5NkqrZJVILn4VPbo2afG-zyvZIfgsBrnRoe-MkMQjdJc5TdAsseFh8rB6HqJRlcWdDoXQTC0wFvNMSPGk-PbMcW7orrjtyDQEJqvTiaUzLAAZMGQ-4ldr4OtJZ1o3DoKPpGWdAt5NNDOocklyDyvny298A7zwtA0g4mIhwnjsWyl__BA4arG",
                "created_at" => "2026-03-25 11:30:00",
                "updated_at" => "2026-03-25 11:30:00",
            ],
            [
                "name" => "Estanque de los Cisnes",
                "type" => "suave",
                "description" => "Barcas infantiles con forma de cisne.",
                "duration" => 5,
                "max_capacity" => 4,
                "min_height" => 0.80,
                "status" => "operational",
                "park_id" => 2,
                "image" => "https://lh3.googleusercontent.com/aida-public/AB6AXuCFsEt5IDp4eM3zxQA_qXlmCTKvlR_kWL1l9nQ2uAotEcuvEHEggiUvGBRn8Qwx3jKLnhW2Frj7gBCi8egjueurnHnF5NkqrZJVILn4VPbo2afG-zyvZIfgsBrnRoe-MkMQjdJc5TdAsseFh8rB6HqJRlcWdDoXQTC0wFvNMSPGk-PbMcW7orrjtyDQEJqvTiaUzLAAZMGQ-4ldr4OtJZ1o3DoKPpGWdAt5NNDOocklyDyvny298A7zwtA0g4mIhwnjsWyl__BA4arG",
                "created_at" => "2026-04-01 09:15:00",
                "updated_at" => "2026-04-01 09:15:00",
            ],
            [
                "name" => "El SurcaOlas Extreme",
                "type" => "moderado",
                "description" => "Más rápido que el original.",
                "duration" => 5,
                "max_capacity" => 20,
                "min_height" => 1.20,
                "status" => "operational",
                "park_id" => 2,
                "image" => "https://lh3.googleusercontent.com/aida-public/AB6AXuCFsEt5IDp4eM3zxQA_qXlmCTKvlR_kWL1l9nQ2uAotEcuvEHEggiUvGBRn8Qwx3jKLnhW2Frj7gBCi8egjueurnHnF5NkqrZJVILn4VPbo2afG-zyvZIfgsBrnRoe-MkMQjdJc5TdAsseFh8rB6HqJRlcWdDoXQTC0wFvNMSPGk-PbMcW7orrjtyDQEJqvTiaUzLAAZMGQ-4ldr4OtJZ1o3DoKPpGWdAt5NNDOocklyDyvny298A7zwtA0g4mIhwnjsWyl__BA4arG",
                "created_at" => "2026-03-20 10:00:00",
                "updated_at" => "2026-03-20 10:00:00",
            ],
            [
                "name" => "Rápidos del Cañón",
                "type" => "moderado",
                "description" => "Descenso entre rocas y cascadas.",
                "duration" => 6,
                "max_capacity" => 10,
                "min_height" => 1.20,
                "status" => "operational",
                "park_id" => 2,
                "image" => "https://lh3.googleusercontent.com/aida-public/AB6AXuCFsEt5IDp4eM3zxQA_qXlmCTKvlR_kWL1l9nQ2uAotEcuvEHEggiUvGBRn8Qwx3jKLnhW2Frj7gBCi8egjueurnHnF5NkqrZJVILn4VPbo2afG-zyvZIfgsBrnRoe-MkMQjdJc5TdAsseFh8rB6HqJRlcWdDoXQTC0wFvNMSPGk-PbMcW7orrjtyDQEJqvTiaUzLAAZMGQ-4ldr4OtJZ1o3DoKPpGWdAt5NNDOocklyDyvny298A7zwtA0g4mIhwnjsWyl__BA4arG",
                "created_at" => "2026-03-28 14:20:00",
                "updated_at" => "2026-03-28 14:20:00",
            ],
            [
                "name" => "Cataratas Prohibidas",
                "type" => "moderado",
                "description" => "Caída libre en la oscuridad.",
                "duration" => 4,
                "max_capacity" => 16,
                "min_height" => 1.15,
                "status" => "closed",
                "park_id" => 2,
                "image" => "https://lh3.googleusercontent.com/aida-public/AB6AXuCFsEt5IDp4eM3zxQA_qXlmCTKvlR_kWL1l9nQ2uAotEcuvEHEggiUvGBRn8Qwx3jKLnhW2Frj7gBCi8egjueurnHnF5NkqrZJVILn4VPbo2afG-zyvZIfgsBrnRoe-MkMQjdJc5TdAsseFh8rB6HqJRlcWdDoXQTC0wFvNMSPGk-PbMcW7orrjtyDQEJqvTiaUzLAAZMGQ-4ldr4OtJZ1o3DoKPpGWdAt5NNDOocklyDyvny298A7zwtA0g4mIhwnjsWyl__BA4arG",
                "created_at" => "2026-04-03 17:45:00",
                "updated_at" => "2026-04-03 17:45:00",
            ],
            [
                "name" => "El Gran Remolino",
                "type" => "intenso",
                "description" => "La versión más grande del remolino.",
                "duration" => 2,
                "max_capacity" => 30,
                "min_height" => 1.40,
                "status" => "operational",
                "park_id" => 2,
                "image" => "https://lh3.googleusercontent.com/aida-public/AB6AXuCFsEt5IDp4eM3zxQA_qXlmCTKvlR_kWL1l9nQ2uAotEcuvEHEggiUvGBRn8Qwx3jKLnhW2Frj7gBCi8egjueurnHnF5NkqrZJVILn4VPbo2afG-zyvZIfgsBrnRoe-MkMQjdJc5TdAsseFh8rB6HqJRlcWdDoXQTC0wFvNMSPGk-PbMcW7orrjtyDQEJqvTiaUzLAAZMGQ-4ldr4OtJZ1o3DoKPpGWdAt5NNDOocklyDyvny298A7zwtA0g4mIhwnjsWyl__BA4arG",
                "created_at" => "2026-03-20 10:00:00",
                "updated_at" => "2026-03-20 10:00:00",
            ],
            [
                "name" => "Tifón del Pacífico",
                "type" => "intenso",
                "description" => "Montaña rusa con 3 loopings.",
                "duration" => 2,
                "max_capacity" => 24,
                "min_height" => 1.50,
                "status" => "operational",
                "park_id" => 2,
                "image" => "https://lh3.googleusercontent.com/aida-public/AB6AXuCFsEt5IDp4eM3zxQA_qXlmCTKvlR_kWL1l9nQ2uAotEcuvEHEggiUvGBRn8Qwx3jKLnhW2Frj7gBCi8egjueurnHnF5NkqrZJVILn4VPbo2afG-zyvZIfgsBrnRoe-MkMQjdJc5TdAsseFh8rB6HqJRlcWdDoXQTC0wFvNMSPGk-PbMcW7orrjtyDQEJqvTiaUzLAAZMGQ-4ldr4OtJZ1o3DoKPpGWdAt5NNDOocklyDyvny298A7zwtA0g4mIhwnjsWyl__BA4arG",
                "created_at" => "2026-03-30 12:00:00",
                "updated_at" => "2026-03-30 12:00:00",
            ],
            [
                "name" => "La Furia del Kraken",
                "type" => "intenso",
                "description" => "Atracción hermana del Abismo.",
                "duration" => 3,
                "max_capacity" => 12,
                "min_height" => 1.45,
                "status" => "operational",
                "park_id" => 2,
                "image" => "https://lh3.googleusercontent.com/aida-public/AB6AXuCFsEt5IDp4eM3zxQA_qXlmCTKvlR_kWL1l9nQ2uAotEcuvEHEggiUvGBRn8Qwx3jKLnhW2Frj7gBCi8egjueurnHnF5NkqrZJVILn4VPbo2afG-zyvZIfgsBrnRoe-MkMQjdJc5TdAsseFh8rB6HqJRlcWdDoXQTC0wFvNMSPGk-PbMcW7orrjtyDQEJqvTiaUzLAAZMGQ-4ldr4OtJZ1o3DoKPpGWdAt5NNDOocklyDyvny298A7zwtA0g4mIhwnjsWyl__BA4arG",
                "created_at" => "2026-04-05 16:30:00",
                "updated_at" => "2026-04-05 16:30:00",
            ],
        ]);

    }
}
