name: Deploy Mundo Marino

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Actualizar VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            git config --global --add safe.directory /var/www/tfg

            # 1. ACTIVAR MANTENIMIENTO Y APUNTAR NGINX A LARAVEL
            cd /var/www/tfg/Mundo_Marino_back
            php artisan down --refresh=15 --redirect="/" || true

            sudo sed -i 's|root /var/www/tfg/Mundo_Marino_front;|root /var/www/tfg/Mundo_Marino_back/public;|' /etc/nginx/sites-enabled/tu-sitio.conf
            sudo nginx -s reload

            # 2. ACTUALIZAR CÓDIGO
            cd /var/www/tfg
            git fetch origin master
            git reset --hard origin/master

            # 3. --- BACKEND ---
            cd Mundo_Marino_back
            composer install --no-interaction --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache

            # 4. --- FRONTEND ---
            cd /var/www/tfg/Mundo_Marino_front
            npm install
            npm run build -- --configuration=production

            # 5. RESTAURAR NGINX Y FINALIZAR
            sudo sed -i 's|root /var/www/tfg/Mundo_Marino_back/public;|root /var/www/tfg/Mundo_Marino_front;|' /etc/nginx/sites-enabled/tu-sitio.conf
            sudo nginx -s reload

            cd /var/www/tfg/Mundo_Marino_back
            php artisan up

            echo "¡Despliegue finalizado con éxito!"